[build-system]
requires = ["setuptools>=64", "wheel"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "rag-telecom-chatbot"
version = "0.1.0"
description = "RAG-based telecom customer care chatbot tutorial"
requires-python = ">=3.10,<3.14"
dependencies = [
    "langchain",
    "langchain-core",
    "langchain-groq",
    "pandas",
    "python-dotenv",
    "streamlit",
    "fpdf2",
    "pypdf",
    "langchain-community",
    "langchain-text-splitters",
    "datasets",
    "ragas",
]

[tool.setuptools.packages.find]
include = ["ci*", "validation*"]