[server]
headless = true
address = "127.0.0.1"
port = 8501
fileWatcherType = "none"
runOnSave = false
websocketPingInterval = 30
disconnectedSessionTTL = 600

[browser]
gatherUsageStats = false
serverAddress = "127.0.0.1"
serverPort = 8501
